### ISSUE TITLE
Error Handling for OpsCenter Start Failure or Delay

### ISSUE THREAD

**Issue by mahthi** [DSPN/azure-arm-dse#28]
Need to update the opscenter script with a method to reliably check if Opscenter instead of sleeping for 200 seconds. This will shave ~3 minutes from a ~22 minute deployment for 90 nodes.

**Comment by benofben** [comment]
If OpsCenter responds with an HTTP 200, then it is running.  So, it would be possible to just make a call to the login page like so:
curl http://path-to-ops:8888

We could potentially put this in a polling loop in the script.  Need to think about the best way to do that...

**Comment by mahthi** [comment]
Okay. Can we leave this issue open till that work is complete?

**Comment by benofben** [comment]
Reopened.  Not certain this polling behavior is the best solution.  I'd strongly prefer to have something that looks more like proper error handling.  We understand that the APIs are changing significantly in the next release.  Rather than spending a lot of effort on this now, I'd prefer to wait until those APIs stabilize.

**Comment by benofben** [comment]
I should also note, that I've turned the sleep down to 15 seconds again.  The time it takes OpsCenter to come up is not dependent on the number of nodes (since the first time it starts, it is unaware how big the cluster will eventually be).

That said, waiting between calls and handling failures would be desirable.

**Comment by mahthi** [comment]
Okay!

**Comment by benofben** [comment]
I haven't observed this issue in some time.  I believe we've resolved it.
