### ISSUE TITLE
Switch to OpenJDK

### ISSUE THREAD

**Issue by stinkymatt** [DSPN/azure-arm-dse#37]
OpenJDK 7 recently became a supported VM for DSE. OpenJDK 8 is on deck for 4.7.2. We should switch the templates to use that.

**Comment by benofben** [comment]
Investigating JDK options.  The current constraint is the repo.

Canonical -- only has OpenJDK 7 in the repo.  Been told to prefer 8 over that for GC performance reasons.

Azure Zulu -- has OpenJDK 8 but repo times out.  Speaking with them about a mirror in Azure.

Oracle JVM -- potential license concerns.  Repo also times out under extreme load.

**Comment by benofben** [comment]
I've updated the template to use the OpenJDK 7 which ships with Ubuntu.

Azul has also written back saying their repos have been updated and may work more reliably.  Need to test with that.  It may be preferable as the Azul Zulu VM seems to be smaller and have fewer packages which means it installs faster than the standard OpenJDK that ships with the OS.  I don't have a measurement of exactly how much faster.

**Comment by benofben** [comment]
The templates have been revised to use Azul Zulu.  This is a flavor of OpenJDK which we selected because it:
(a) ships as fewer packages than the Canonical default-jre
(b) does not include graphics components that we aren't going to use

The Azul repos seem to be holding up to the load of spinning 90 node clusters.  The Azul team is responsive in enhancing the repos as well.
